module Audio exposing (url)

import Dict exposing (Dict)


prefixes : Dict String String
prefixes =
    [ ( "Audio/Dialogue/Character/Str", "https://oriath.net/Characters/Marauder/" )
    , ( "Audio/Dialogue/Character/Dex", "https://oriath.net/Characters/Ranger/" )
    , ( "Audio/Dialogue/Character/Int", "https://oriath.net/Characters/Witch/" )
    , ( "Audio/Dialogue/Character/StrDex", "https://oriath.net/Characters/Duelist/" )
    , ( "Audio/Dialogue/Character/StrInt", "https://oriath.net/Characters/Templar/" )
    , ( "Audio/Dialogue/Character/DexInt", "https://oriath.net/Characters/Shadow/" )
    , ( "Audio/Dialogue/Character/StrDexInt", "https://oriath.net/Characters/Scion/" )
    , ( "Audio/Dialogue/NPC/JackTheAxeArea", "https://oriath.net/Items/Jack_The_Axe/" )
    , ( "Audio/Dialogue/NPC/JackTheAxe", "https://oriath.net/Items/Jack_The_Axe/" )
    , ( "Audio/Dialogue/Goddess_Unleashed", "https://oriath.net/Items/Charans_Sword/" )
    , ( "Audio/Dialogue/NPC/Izaro", "https://oriath.net/Labyrinth/Izaro/" )
    , ( "Audio/Dialogue/NPC/BeachGuy", "https://oriath.net/Acts/Act_1/Beach_Guy/" )
    , ( "Audio/Dialogue/NPC/Bestel", "https://oriath.net/Acts/Act_1/Bestel/" )
    , ( "Audio/Dialogue/NPC/Brute", "https://oriath.net/Acts/Act_1/Brutus/" )
    , ( "Audio/Dialogue/NPC/BruteCombat", "https://oriath.net/Acts/Act_1/Brutus/" )
    , ( "Audio/Dialogue/NPC/DoorGuy", "https://oriath.net/Acts/Act_1/Door_Guy/" )
    , ( "Audio/Dialogue/NPC/Fairgraves", "https://oriath.net/Acts/Act_1/Fairgraves/" )
    , ( "Audio/Dialogue/Glyph", "https://oriath.net/Acts/Act_1/Lavianga/" )
    , ( "Audio/Dialogue/NPC/Merveil", "https://oriath.net/Acts/Act_1/Merveil/" )
    , ( "Audio/Dialogue/NPC/MerveilArea", "https://oriath.net/Acts/Act_1/Merveil/" )
    , ( "Audio/Dialogue/NPC/MerveilCombat", "https://oriath.net/Acts/Act_1/Merveil/" )
    , ( "Audio/Dialogue/NPC/Nessa", "https://oriath.net/Acts/Act_1/Nessa/" )
    , ( "Audio/Dialogue/NPC/Tarkleigh", "https://oriath.net/Acts/Act_1/Tarkleigh/" )
    , ( "Audio/Dialogue/NPC/Alira", "https://oriath.net/Acts/Act_2/Alira/" )
    , ( "Audio/Dialogue/NPC/Eramir", "https://oriath.net/Acts/Act_2/Eramir/" )
    , ( "Audio/Dialogue/NPC/Greust", "https://oriath.net/Acts/Act_2/Greust/" )
    , ( "Audio/Dialogue/NPC/Helyna", "https://oriath.net/Acts/Act_2/Helena/" )
    , ( "Audio/Dialogue/NPC/Kraityn", "https://oriath.net/Acts/Act_2/Kraityn/" )
    , ( "Audio/Dialogue/NPC/Oak", "https://oriath.net/Acts/Act_2/Oak/" )
    , ( "Audio/Dialogue/NPC/Piety", "https://oriath.net/Acts/Act_2/Piety/" )
    , ( "Audio/Dialogue/NPC/Silk", "https://oriath.net/Acts/Act_2/Silk/" )
    , ( "Audio/Dialogue/NPC/Tani", "https://oriath.net/Acts/Act_2/Tani/" )
    , ( "Audio/Dialogue/NPC/Yeena", "https://oriath.net/Acts/Act_2/Yeena/" )
    , ( "Audio/Dialogue/NPC/Clarissa", "https://oriath.net/Acts/Act_3/Clarissa/" )
    , ( "Audio/Dialogue/NPC/Dominus", "https://oriath.net/Acts/Act_3/Dominus/" )
    , ( "Audio/Dialogue/NPC/DominusCombat", "https://oriath.net/Acts/Act_3/Dominus/" )
    , ( "Audio/Dialogue/NPC/DominusGlyph", "https://oriath.net/Acts/Act_3/Dominus/" )
    , ( "Audio/Dialogue/NPC/Gravicius", "https://oriath.net/Acts/Act_3/Gravicius/" )
    , ( "Audio/Dialogue/NPC/GraviciusCombat", "https://oriath.net/Acts/Act_3/Gravicius/" )
    , ( "Audio/Dialogue/NPC/Grigor", "https://oriath.net/Acts/Act_3/Grigor/" )
    , ( "Audio/Dialogue/NPC/Hargan", "https://oriath.net/Acts/Act_3/Hargan/" )
    , ( "Audio/Dialogue/NPC/Maramoa", "https://oriath.net/Acts/Act_3/Maramoa/" )
    , ( "Audio/Dialogue/NPC/Siosa", "https://oriath.net/Acts/Act_3/Siosa/" )
    , ( "Audio/Dialogue/NPC/Victario", "https://oriath.net/Acts/Act_3/Victario/" )
    , ( "Audio/Dialogue/NPC/Barkhul", "https://oriath.net/Acts/Act_4/Barkhul/" )
    , ( "Audio/Dialogue/NPC/Daresso", "https://oriath.net/Acts/Act_4/Daresso/" )
    , ( "Audio/Dialogue/NPC/Dialla", "https://oriath.net/Acts/Act_4/Dialla/" )
    , ( "Audio/Dialogue/NPC/Irasha", "https://oriath.net/Acts/Act_4/Irasha/" )
    , ( "Audio/Dialogue/NPC/Kaom", "https://oriath.net/Acts/Act_4/Kaom/" )
    , ( "Audio/Dialogue/NPC/KaomCombat", "https://oriath.net/Acts/Act_4/Kaom/" )
    , ( "Audio/Dialogue/NPC/KaomGlyph", "https://oriath.net/Acts/Act_4/Kaom/" )
    , ( "Audio/Dialogue/NPC/Kira", "https://oriath.net/Acts/Act_4/Kira/" )
    , ( "Audio/Dialogue/NPC/Malachai", "https://oriath.net/Acts/Act_4/Malachai/" )
    , ( "Audio/Dialogue/NPC/MalachaiCombat", "https://oriath.net/Acts/Act_4/Malachai/" )
    , ( "Audio/Dialogue/NPC/MalachaiCombatS", "https://oriath.net/Acts/Act_4/Malachai/" )
    , ( "Audio/Dialogue/NPC/MalachaiS", "https://oriath.net/Acts/Act_4/Malachai/" )
    , ( "Audio/Dialogue/NPC/MalachaiGlyph", "https://oriath.net/Acts/Act_4/Malachai/" )
    , ( "Audio/Dialogue/NPC/Maligaro", "https://oriath.net/Acts/Act_4/Maligaro/" )
    , ( "Audio/Dialogue/NPC/MaligaroCombat", "https://oriath.net/Acts/Act_4/Maligaro/" )
    , ( "Audio/Dialogue/NPC/Oyun", "https://oriath.net/Acts/Act_4/Oyun/" )
    , ( "Audio/Dialogue/NPC/PetarusAndVanja", "https://oriath.net/Acts/Act_4/Petarus_and_Vanja/" )
    , ( "Audio/Dialogue/NPC/Shavronne", "https://oriath.net/Acts/Act_4/Shavronne/" )
    , ( "Audio/Dialogue/NPC/ShavronneCombat", "https://oriath.net/Acts/Act_4/Shavronne/" )
    , ( "Audio/Dialogue/NPC/ShavronneGlyph", "https://oriath.net/Acts/Act_4/Shavronne/" )
    , ( "Audio/Dialogue/NPC/Tasuni", "https://oriath.net/Acts/Act_4/Tasuni/" )
    , ( "Audio/Dialogue/NPC/Voll", "https://oriath.net/Acts/Act_4/Voll/" )
    , ( "Audio/Dialogue/NPC/VollCombat", "https://oriath.net/Acts/Act_4/Voll/" )
    , ( "Audio/Dialogue/NPC/Avarius", "https://oriath.net/Acts/Act_5/Avarius/" )
    , ( "Audio/Dialogue/NPC/AvariusIntro", "https://oriath.net/Acts/Act_5/Avarius/" )
    , ( "Audio/Dialogue/NPC/AvariusStereo", "https://oriath.net/Acts/Act_5/Avarius/" )
    , ( "Audio/Dialogue/NPC/Bannon", "https://oriath.net/Acts/Act_5/Bannon/" )
    , ( "Audio/Dialogue/NPC/Bannon3D", "https://oriath.net/Acts/Act_5/Bannon/" )
    , ( "Audio/Dialogue/NPC/Innocence", "https://oriath.net/Acts/Act_5/Innocence/" )
    , ( "Audio/Dialogue/NPC/InnocenceCombat", "https://oriath.net/Acts/Act_5/Innocence/" )
    , ( "Audio/Dialogue/NPC/Lani", "https://oriath.net/Acts/Act_5/Lani/" )
    , ( "Audio/Dialogue/NPC/Sin", "https://oriath.net/Acts/Act_5/Sin/" )
    , ( "Audio/Dialogue/NPC/Utula", "https://oriath.net/Acts/Act_5/Utula/" )
    , ( "Audio/Dialogue/NPC/Vilenta", "https://oriath.net/Acts/Act_5/Vilenta/" )
    , ( "Audio/Dialogue/NPC/Lilly", "https://oriath.net/Acts/Act_6/Lilly_Roth/" )
    , ( "Audio/Dialogue/NPC/NessaFishwife", "https://oriath.net/Acts/Act_6/Nessa/" )
    , ( "Audio/Dialogue/NPC/TukohamaCombat", "https://oriath.net/Acts/Act_6/Tukohama/" )
    , ( "Audio/Dialogue/NPC/TukohamaIntro", "https://oriath.net/Acts/Act_6/Tukohama/" )
    , ( "Audio/Dialogue/NPC/Weylam", "https://oriath.net/Acts/Act_6/Weylam_Roth/" )
    , ( "Audio/Dialogue/NPC/Solaris", "https://oriath.net/Acts/Act_8/Solaris_and_Lunaris/" )
    , ( "Audio/Dialogue/NPC/Lunaris", "https://oriath.net/Acts/Act_8/Solaris_and_Lunaris/" )
    , ( "Audio/Dialogue/NPC/Kirac", "https://oriath.net/Acts/Endgame/Kirac/" )
    , ( "Audio/Dialogue/NPC/Zana", "https://oriath.net/Acts/Endgame/Zana/" )
    , ( "Audio/Dialogue/NPC/ZanaCombat", "https://oriath.net/Acts/Endgame/Zana/" )
    , ( "Audio/Dialogue/NPC/ZanaCombatNarrator", "https://oriath.net/Acts/Endgame/Zana/" )
    , ( "Audio/Dialogue/NPC/ZanaNarrator", "https://oriath.net/Acts/Endgame/Zana/" )
    , ( "Audio/Dialogue/NPC/Al-Hezmin", "https://oriath.net/Acts/Endgame/Al-Hezmin/" )
    , ( "Audio/Dialogue/NPC/Al-HezminCombat", "https://oriath.net/Acts/Endgame/Al-Hezmin/" )
    , ( "Audio/Dialogue/NPC/BaranTheCrusader", "https://oriath.net/Acts/Endgame/Baran/" )
    , ( "Audio/Dialogue/NPC/BaranTheCrusaderCombat", "https://oriath.net/Acts/Endgame/Baran/" )
    , ( "Audio/Dialogue/NPC/DroxTheWarlord", "https://oriath.net/Acts/Endgame/Drox/" )
    , ( "Audio/Dialogue/NPC/DroxTheWarlordCombat", "https://oriath.net/Acts/Endgame/Drox/" )
    , ( "Audio/Dialogue/NPC/Veritania", "https://oriath.net/Acts/Endgame/Veritania/" )
    , ( "Audio/Dialogue/NPC/VeritaniaCombat", "https://oriath.net/Acts/Endgame/Veritania/" )
    , ( "Audio/Dialogue/NPC/Sirus", "https://oriath.net/Acts/Endgame/Sirus/" )
    , ( "Audio/Dialogue/NPC/SirusCombat", "https://oriath.net/Acts/Endgame/Sirus/" )
    , ( "Audio/Dialogue/NPC/ShaperNarrator", "https://oriath.net/Acts/Endgame/Shaper/" )
    , ( "Audio/Dialogue/NPC/ShaperGlyph", "https://oriath.net/Acts/Endgame/Shaper/" )
    , ( "Audio/Dialogue/NPC/ShaperCombat", "https://oriath.net/Acts/Endgame/Shaper/" )
    , ( "Audio/Dialogue/NPC/ShaperCombatNarrator", "https://oriath.net/Acts/Endgame/Shaper/" )
    , ( "Audio/Dialogue/NPC/Weylin", "https://oriath.net/Labyrinth/Weylin/" )
    , ( "Audio/Dialogue/NPC/Rigwald", "https://oriath.net/League/Talisman/Rigwald/" )
    , ( "Audio/Dialogue/NPC/RigwaldCombat", "https://oriath.net/League/Talisman/Rigwald/" )
    , ( "Audio/Dialogue/NPC/RigwaldGlyph", "https://oriath.net/League/Talisman/Rigwald/" )
    , ( "Audio/Dialogue/NPC/Cadiro", "https://oriath.net/League/Perandus/Cadiro/" )
    , ( "Audio/Dialogue/NPC/Navali", "https://oriath.net/League/Prophecy/Navali/" )
    , ( "Audio/Dialogue/NPC/NavaliProphecy", "https://oriath.net/League/Prophecy/Navali/" )
    , ( "Audio/Dialogue/NPC/Einhar", "https://oriath.net/League/Bestiary/Einhar/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Einhar", "https://oriath.net/League/Bestiary/Einhar/" )
    , ( "Audio/Dialogue/NPC/Alva", "https://oriath.net/League/Incursion/Alva/" )
    , ( "Audio/Dialogue/NPC/AlvaModern", "https://oriath.net/League/Incursion/Alva/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Alva", "https://oriath.net/League/Incursion/Alva/" )
    , ( "Audio/Dialogue/NPC/Niko", "https://oriath.net/League/Delve/Niko/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Niko", "https://oriath.net/League/Delve/Niko/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Aisling", "https://oriath.net/League/Betrayal/Aisling/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Cameria", "https://oriath.net/League/Betrayal/Cameria/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Catarina", "https://oriath.net/League/Betrayal/Catarina/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/CatarinaGlyph", "https://oriath.net/League/Betrayal/Catarina/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Elreon", "https://oriath.net/League/Betrayal/Elreon/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Gravicius", "https://oriath.net/League/Betrayal/Gravicius/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Guff", "https://oriath.net/League/Betrayal/Guff/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Haku", "https://oriath.net/League/Betrayal/Haku/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Hillock", "https://oriath.net/League/Betrayal/Hillock/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Hillock", "https://oriath.net/League/Betrayal/Hillock/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/ItThatFled", "https://oriath.net/League/Betrayal/It_That_Fled/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Janus", "https://oriath.net/League/Betrayal/Janus_Perandus/" )
    , ( "Audio/Dialogue/NPC/JunOrtoi", "https://oriath.net/League/Betrayal/Jun/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Korell", "https://oriath.net/League/Betrayal/Korell_Goya/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Leo", "https://oriath.net/League/Betrayal/Leo/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Riker", "https://oriath.net/League/Betrayal/Riker_Maloney/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Rin", "https://oriath.net/League/Betrayal/Rin_Yuushu/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Thane", "https://oriath.net/League/Betrayal/Thane_Jorgin/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Tora", "https://oriath.net/League/Betrayal/Tora/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Vagan", "https://oriath.net/League/Betrayal/Vagan/" )
    , ( "Audio/Dialogue/NPC/BetrayalLeague/Vorici", "https://oriath.net/League/Betrayal/Vorici/" )
    , ( "Audio/Dialogue/NPC/Cavas", "https://oriath.net/League/Synthesis/Cavas/" )
    , ( "Audio/Dialogue/NPC/CavasCombat", "https://oriath.net/League/Synthesis/Cavas/" )
    , ( "Audio/Dialogue/NPC/CavasNarrator", "https://oriath.net/League/Synthesis/Cavas/" )
    , ( "Audio/Dialogue/NPC/Aukuna", "https://oriath.net/League/Legion/Aukuna/" )
    , ( "Audio/Dialogue/NPC/Hyrri", "https://oriath.net/League/Legion/Hyrri_Ngamaku/" )
    , ( "Audio/Dialogue/NPC/Lioneye", "https://oriath.net/League/Legion/Marceus_Lioneye/" )
    , ( "Audio/Dialogue/NPC/Vox", "https://oriath.net/League/Legion/Sanctus_Vox/" )
    , ( "Audio/Dialogue/NPC/Viper", "https://oriath.net/League/Legion/Viper_Napuatzi/" )
    , ( "Audio/Dialogue/NPC/Cassia", "https://oriath.net/League/Blight/Cassia/" )
    , ( "Audio/Dialogue/NPC/CassiaCombat", "https://oriath.net/League/Blight/Cassia/" )
    , ( "Audio/Dialogue/NPC/CassiaSing", "https://oriath.net/League/Blight/Cassia/" )
    , ( "Audio/Dialogue/NPC/Tane", "https://oriath.net/League/Metamorph/Tane/" )
    , ( "Audio/Dialogue/NPC/Delirium", "https://oriath.net/League/Delirium/Tangmazu/" )
    , ( "Audio/Dialogue/NPC/Oshabi", "https://oriath.net/League/Harvest/Oshabi/" )
    , ( "Audio/Dialogue/NPC/OshabiBoss", "https://oriath.net/League/Harvest/Oshabi/" )
    , ( "Audio/Dialogue/NPC/Atziri", "https://oriath.net/Vaal/Atziri/" )
    , ( "Audio/Dialogue/NPC/Catarina", "https://oriath.net/Masters/Catarina/" )
    , ( "Audio/Dialogue/NPC/Vorici", "https://oriath.net/Masters/Vorici/" )
    , ( "Audio/Dialogue/NPC/Tora", "https://oriath.net/Masters/Tora/" )
    , ( "Audio/Dialogue/NPC/Vagan", "https://oriath.net/Masters/Vagan/" )
    , ( "Audio/Dialogue/NPC/VaganCombat", "https://oriath.net/Masters/Vagan/" )
    , ( "Audio/Dialogue/NPC/Haku", "https://oriath.net/Masters/Haku/" )
    , ( "Audio/Dialogue/NPC/Elreon", "https://oriath.net/Masters/Elreon/" )
    , ( "Audio/Dialogue/NPC/Zana_Old", "https://oriath.net/Masters/Original_Zana/" )
    , ( "Audio/Dialogue/NPC/Leo", "https://oriath.net/Masters/Leo/" )
    , ( "Audio/Dialogue/Character/StrDexInt/Misc", "https://oriath.net/Masters/Krillson/" )
    , ( "Audio/Dialogue/NPC/DaughterOfSinPet", "https://oriath.net/Misc/Daughter_of_Sin_Pet/" )
    , ( "Audio/Dialogue/PVP_Announcer", "https://oriath.net/Misc/PvP_Announcer/" )
    ]
        |> Dict.fromList


url : String -> Maybe String
url str =
    if String.endsWith ".ogg" str then
        let
            segments =
                String.split "/" str
        in
        [ List.take 3 segments, List.take 4 segments, List.take 5 segments ]
            |> List.map (String.join "/")
            |> List.filterMap (\pre -> Dict.get pre prefixes)
            |> List.head
            |> Maybe.withDefault "https://oriath.net/audio-index.html"
            |> Just

    else
        Nothing
