name: continuous-deployment

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - run: yarn lint
      # Create and deploy a Netlify site on push, or a preview on pull-request.
      # https://github.com/netlify/actions/tree/master/build
      # You'll need to add this repo to netlify's github application for this to work: https://github.com/settings/installations
      - name: Deploy to Netlify
        id: deploy-netlify
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_CMD: yarn install --frozen-lockfile && yarn build
          NETLIFY_DIR: build
